baseURL = "https://salprima.github.io/"
languageCode = "en-us"
title = "I Code You"
theme = "minimal"
disqusShortname = "dprimax" # delete this to disable disqus comments
googleAnalytics = ""

[params]
    author = "Sal Prima"
    description = "Like I ❤ You"
    githubUsername = "dprimax"
    accent = "#8b6b61"
    showBorder = true
    backgroundColor = "#321911"
    font = "Ubuntu" # should match the name on Google Fonts!
    highlight = true
    highlightStyle = "atom-one-dark"
    highlightLanguages = ["go", "java", "javascript", "html", "css"]
    copyright = "&copy; 2018 [salprima](https://salprima.github.io) All rights reserved. Powered by [Hugo](https://gohugo.io) and [Minimal](https://github.com/calintat/minimal)"

[[menu.main]]
    url = "/"
    name = "Home"
    weight = 1

[[menu.main]]
    url = "/posts"
    name = "Posts"
    weight = 2

[[menu.main]]
    url = "/tags"
    name = "Tags"
    weight = 3

#[[menu.main]]
#    url = "/about"
#    name = "About"
#    weight = 4
# Social icons to be shown on the right-hand side of the navigation bar
# The "name" field should match the name of the icon to be used
# The list of available icons can be found at http://fontawesome.io/icons/

[[menu.icon]]
    url = "mailto:dprima10@gmail.com"
    name = "envelope-o"
    weight = 1

[[menu.icon]]
    url = "https://github.com/salrprima"
    name = "github"
    weight = 2

[[menu.icon]]
    url = "https://twitter.com/dprimax"
    name = "twitter"
    weight = 3

[[menu.icon]]
    url = "https://www.linkedin.com/in/salprima"
    name = "linkedin"
    weight = 4

[[menu.icon]]
    url = "https://stackoverflow.com/users/494121"
    name = "stack-overflow"
    weight = 5
